### ISSUE TITLE
Creator can not delete requirements

### ISSUE THREAD

**Issue by aparkova** [rwth-acis/RequirementsBazaar-WebFrontend#236] opened 2022-04-26 14:36 UTC
Error message pops up: "Only the creator can delete requirements.", but the creator is also unable to delete created requirements.

**Comment by fxjordan** [comment] 2022-04-26 15:55
Duplicate of https://github.com/rwth-acis/RequirementsBazaar-WebFrontend/issues/147

**Closed by fxjordan** 2022-04-26 15:55 UTC
